services:
  verifier-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: verifier-api
    ports:
      - "5001:8080"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - lab-network

networks:
  lab-network:
    external: true
